/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconClarityCloseLine: typeof import('~icons/clarity/close-line')['default']
    IconClarityPinLine: typeof import('~icons/clarity/pin-line')['default']
    IconClarityPinSolid: typeof import('~icons/clarity/pin-solid')['default']
    IconFluentSettings24Regular: typeof import('~icons/fluent/settings24-regular')['default']
    IconGravityUiChevronsUp: typeof import('~icons/gravity-ui/chevrons-up')['default']
    IconGravityUiCopy: typeof import('~icons/gravity-ui/copy')['default']
    IconGravityUiPencilToSquare: typeof import('~icons/gravity-ui/pencil-to-square')['default']
    IconGravityUiSquareDashedText: typeof import('~icons/gravity-ui/square-dashed-text')['default']
    IconGravityUiVolume: typeof import('~icons/gravity-ui/volume')['default']
    IconHeroiconsChatBubbleLeftRight: typeof import('~icons/heroicons/chat-bubble-left-right')['default']
    IconHeroiconsSolidSwitchHorizontal: typeof import('~icons/heroicons-solid/switch-horizontal')['default']
    IconIcRoundStop: typeof import('~icons/ic/round-stop')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
