/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconClarityCloseLine: typeof import('~icons/clarity/close-line')['default']
    IconClarityMinusLine: typeof import('~icons/clarity/minus-line')['default']
    IconClarityWindowMaxLine: typeof import('~icons/clarity/window-max-line')['default']
    IconClarityWindowRestoreLine: typeof import('~icons/clarity/window-restore-line')['default']
    IconGravityUiArrowUpFromSquare: typeof import('~icons/gravity-ui/arrow-up-from-square')['default']
    IconGravityUiCheck: typeof import('~icons/gravity-ui/check')['default']
    IconGravityUiCirclePlus: typeof import('~icons/gravity-ui/circle-plus')['default']
    IconGravityUiEllipsisVertical: typeof import('~icons/gravity-ui/ellipsis-vertical')['default']
    IconGravityUiListUl: typeof import('~icons/gravity-ui/list-ul')['default']
    IconGravityUiPencilToSquare: typeof import('~icons/gravity-ui/pencil-to-square')['default']
    IconGravityUiPlus: typeof import('~icons/gravity-ui/plus')['default']
    IconGravityUiTrashBin: typeof import('~icons/gravity-ui/trash-bin')['default']
    IconGravityUiXmark: typeof import('~icons/gravity-ui/xmark')['default']
    IconSvgsLnb: typeof import('~icons/svgs/lnb')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
