/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconClarityCloseLine: typeof import('~icons/clarity/close-line')['default']
    IconClarityMinusLine: typeof import('~icons/clarity/minus-line')['default']
    IconClarityPinLine: typeof import('~icons/clarity/pin-line')['default']
    IconClarityPinSolid: typeof import('~icons/clarity/pin-solid')['default']
    IconClarityWindowMaxLine: typeof import('~icons/clarity/window-max-line')['default']
    IconClarityWindowRestoreLine: typeof import('~icons/clarity/window-restore-line')['default']
    IconGravityUiArrowDownToSquare: typeof import('~icons/gravity-ui/arrow-down-to-square')['default']
    IconGravityUiArrowUpFromSquare: typeof import('~icons/gravity-ui/arrow-up-from-square')['default']
    IconGravityUiCheck: typeof import('~icons/gravity-ui/check')['default']
    IconGravityUiChevronsUp: typeof import('~icons/gravity-ui/chevrons-up')['default']
    IconGravityUiCirclePlus: typeof import('~icons/gravity-ui/circle-plus')['default']
    IconGravityUiCopy: typeof import('~icons/gravity-ui/copy')['default']
    IconGravityUiEllipsisVertical: typeof import('~icons/gravity-ui/ellipsis-vertical')['default']
    IconGravityUiListUl: typeof import('~icons/gravity-ui/list-ul')['default']
    IconGravityUiPencilToSquare: typeof import('~icons/gravity-ui/pencil-to-square')['default']
    IconGravityUiPlus: typeof import('~icons/gravity-ui/plus')['default']
    IconGravityUiSquareDashedText: typeof import('~icons/gravity-ui/square-dashed-text')['default']
    IconGravityUiTrashBin: typeof import('~icons/gravity-ui/trash-bin')['default']
    IconGravityUiVolume: typeof import('~icons/gravity-ui/volume')['default']
    IconGravityUiXmark: typeof import('~icons/gravity-ui/xmark')['default']
    IconHeroiconsSolidSwitchHorizontal: typeof import('~icons/heroicons-solid/switch-horizontal')['default']
    IconIcRoundStop: typeof import('~icons/ic/round-stop')['default']
    IconMdiGoogleTranslate: typeof import('~icons/mdi/google-translate')['default']
    IconMdiPinOff: typeof import('~icons/mdi/pin-off')['default']
    IconSvgsDeeplLogo: typeof import('~icons/svgs/deepl-logo')['default']
    IconSvgsLnb: typeof import('~icons/svgs/lnb')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
